TYPE=VIEW
query=select `video90`.`episode`.`idEpisode` AS `idEpisode`,`video90`.`episode`.`idFile` AS `idFile`,`video90`.`episode`.`c00` AS `c00`,`video90`.`episode`.`c01` AS `c01`,`video90`.`episode`.`c02` AS `c02`,`video90`.`episode`.`c03` AS `c03`,`video90`.`episode`.`c04` AS `c04`,`video90`.`episode`.`c05` AS `c05`,`video90`.`episode`.`c06` AS `c06`,`video90`.`episode`.`c07` AS `c07`,`video90`.`episode`.`c08` AS `c08`,`video90`.`episode`.`c09` AS `c09`,`video90`.`episode`.`c10` AS `c10`,`video90`.`episode`.`c11` AS `c11`,`video90`.`episode`.`c12` AS `c12`,`video90`.`episode`.`c13` AS `c13`,`video90`.`episode`.`c14` AS `c14`,`video90`.`episode`.`c15` AS `c15`,`video90`.`episode`.`c16` AS `c16`,`video90`.`episode`.`c17` AS `c17`,`video90`.`episode`.`c18` AS `c18`,`video90`.`episode`.`c19` AS `c19`,`video90`.`episode`.`c20` AS `c20`,`video90`.`episode`.`c21` AS `c21`,`video90`.`episode`.`c22` AS `c22`,`video90`.`episode`.`c23` AS `c23`,`video90`.`episode`.`idShow` AS `idShow`,`video90`.`files`.`strFilename` AS `strFileName`,`video90`.`path`.`strPath` AS `strPath`,`video90`.`files`.`playCount` AS `playCount`,`video90`.`files`.`lastPlayed` AS `lastPlayed`,`video90`.`files`.`dateAdded` AS `dateAdded`,`video90`.`tvshow`.`c00` AS `strTitle`,`video90`.`tvshow`.`c14` AS `strStudio`,`video90`.`tvshow`.`c05` AS `premiered`,`video90`.`tvshow`.`c13` AS `mpaa`,`video90`.`bookmark`.`timeInSeconds` AS `resumeTimeInSeconds`,`video90`.`bookmark`.`totalTimeInSeconds` AS `totalTimeInSeconds`,`video90`.`seasons`.`idSeason` AS `idSeason` from (((((`video90`.`episode` join `video90`.`files` on((`video90`.`files`.`idFile` = `video90`.`episode`.`idFile`))) join `video90`.`tvshow` on((`video90`.`tvshow`.`idShow` = `video90`.`episode`.`idShow`))) left join `video90`.`seasons` on(((`video90`.`seasons`.`idShow` = `video90`.`episode`.`idShow`) and (`video90`.`seasons`.`season` = `video90`.`episode`.`c12`)))) join `video90`.`path` on((`video90`.`files`.`idPath` = `video90`.`path`.`idPath`))) left join `video90`.`bookmark` on(((`video90`.`bookmark`.`idFile` = `video90`.`episode`.`idFile`) and (`video90`.`bookmark`.`type` = 1))))
md5=82b02388185bfb620d3aa401ea715828
updatable=0
algorithm=0
definer_user=kodi
definer_host=%
suid=2
with_check_option=0
timestamp=2015-01-23 08:57:52
create-version=1
source=SELECT   episode.*,  files.strFileName AS strFileName,  path.strPath AS strPath,  files.playCount AS playCount,  files.lastPlayed AS lastPlayed,  files.dateAdded AS dateAdded,  tvshow.c00 AS strTitle,  tvshow.c14 AS strStudio,  tvshow.c05 AS premiered,  tvshow.c13 AS mpaa,  bookmark.timeInSeconds AS resumeTimeInSeconds,   bookmark.totalTimeInSeconds AS totalTimeInSeconds,   seasons.idSeason AS idSeason FROM episode  JOIN files ON    files.idFile=episode.idFile  JOIN tvshow ON    tvshow.idShow=episode.idShow  LEFT JOIN seasons ON    seasons.idShow=episode.idShow AND seasons.season=episode.c12  JOIN path ON    files.idPath=path.idPath  LEFT JOIN bookmark ON    bookmark.idFile=episode.idFile AND bookmark.type=1
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `video90`.`episode`.`idEpisode` AS `idEpisode`,`video90`.`episode`.`idFile` AS `idFile`,`video90`.`episode`.`c00` AS `c00`,`video90`.`episode`.`c01` AS `c01`,`video90`.`episode`.`c02` AS `c02`,`video90`.`episode`.`c03` AS `c03`,`video90`.`episode`.`c04` AS `c04`,`video90`.`episode`.`c05` AS `c05`,`video90`.`episode`.`c06` AS `c06`,`video90`.`episode`.`c07` AS `c07`,`video90`.`episode`.`c08` AS `c08`,`video90`.`episode`.`c09` AS `c09`,`video90`.`episode`.`c10` AS `c10`,`video90`.`episode`.`c11` AS `c11`,`video90`.`episode`.`c12` AS `c12`,`video90`.`episode`.`c13` AS `c13`,`video90`.`episode`.`c14` AS `c14`,`video90`.`episode`.`c15` AS `c15`,`video90`.`episode`.`c16` AS `c16`,`video90`.`episode`.`c17` AS `c17`,`video90`.`episode`.`c18` AS `c18`,`video90`.`episode`.`c19` AS `c19`,`video90`.`episode`.`c20` AS `c20`,`video90`.`episode`.`c21` AS `c21`,`video90`.`episode`.`c22` AS `c22`,`video90`.`episode`.`c23` AS `c23`,`video90`.`episode`.`idShow` AS `idShow`,`video90`.`files`.`strFilename` AS `strFileName`,`video90`.`path`.`strPath` AS `strPath`,`video90`.`files`.`playCount` AS `playCount`,`video90`.`files`.`lastPlayed` AS `lastPlayed`,`video90`.`files`.`dateAdded` AS `dateAdded`,`video90`.`tvshow`.`c00` AS `strTitle`,`video90`.`tvshow`.`c14` AS `strStudio`,`video90`.`tvshow`.`c05` AS `premiered`,`video90`.`tvshow`.`c13` AS `mpaa`,`video90`.`bookmark`.`timeInSeconds` AS `resumeTimeInSeconds`,`video90`.`bookmark`.`totalTimeInSeconds` AS `totalTimeInSeconds`,`video90`.`seasons`.`idSeason` AS `idSeason` from (((((`video90`.`episode` join `video90`.`files` on((`video90`.`files`.`idFile` = `video90`.`episode`.`idFile`))) join `video90`.`tvshow` on((`video90`.`tvshow`.`idShow` = `video90`.`episode`.`idShow`))) left join `video90`.`seasons` on(((`video90`.`seasons`.`idShow` = `video90`.`episode`.`idShow`) and (`video90`.`seasons`.`season` = `video90`.`episode`.`c12`)))) join `video90`.`path` on((`video90`.`files`.`idPath` = `video90`.`path`.`idPath`))) left join `video90`.`bookmark` on(((`video90`.`bookmark`.`idFile` = `video90`.`episode`.`idFile`) and (`video90`.`bookmark`.`type` = 1))))
