TYPE=VIEW
query=select `video90`.`musicvideo`.`idMVideo` AS `idMVideo`,`video90`.`musicvideo`.`idFile` AS `idFile`,`video90`.`musicvideo`.`c00` AS `c00`,`video90`.`musicvideo`.`c01` AS `c01`,`video90`.`musicvideo`.`c02` AS `c02`,`video90`.`musicvideo`.`c03` AS `c03`,`video90`.`musicvideo`.`c04` AS `c04`,`video90`.`musicvideo`.`c05` AS `c05`,`video90`.`musicvideo`.`c06` AS `c06`,`video90`.`musicvideo`.`c07` AS `c07`,`video90`.`musicvideo`.`c08` AS `c08`,`video90`.`musicvideo`.`c09` AS `c09`,`video90`.`musicvideo`.`c10` AS `c10`,`video90`.`musicvideo`.`c11` AS `c11`,`video90`.`musicvideo`.`c12` AS `c12`,`video90`.`musicvideo`.`c13` AS `c13`,`video90`.`musicvideo`.`c14` AS `c14`,`video90`.`musicvideo`.`c15` AS `c15`,`video90`.`musicvideo`.`c16` AS `c16`,`video90`.`musicvideo`.`c17` AS `c17`,`video90`.`musicvideo`.`c18` AS `c18`,`video90`.`musicvideo`.`c19` AS `c19`,`video90`.`musicvideo`.`c20` AS `c20`,`video90`.`musicvideo`.`c21` AS `c21`,`video90`.`musicvideo`.`c22` AS `c22`,`video90`.`musicvideo`.`c23` AS `c23`,`video90`.`files`.`strFilename` AS `strFileName`,`video90`.`path`.`strPath` AS `strPath`,`video90`.`files`.`playCount` AS `playCount`,`video90`.`files`.`lastPlayed` AS `lastPlayed`,`video90`.`files`.`dateAdded` AS `dateAdded`,`video90`.`bookmark`.`timeInSeconds` AS `resumeTimeInSeconds`,`video90`.`bookmark`.`totalTimeInSeconds` AS `totalTimeInSeconds` from (((`video90`.`musicvideo` join `video90`.`files` on((`video90`.`files`.`idFile` = `video90`.`musicvideo`.`idFile`))) join `video90`.`path` on((`video90`.`path`.`idPath` = `video90`.`files`.`idPath`))) left join `video90`.`bookmark` on(((`video90`.`bookmark`.`idFile` = `video90`.`musicvideo`.`idFile`) and (`video90`.`bookmark`.`type` = 1))))
md5=60c7368e56e76a62dc7e7fa61babd9da
updatable=0
algorithm=0
definer_user=kodi
definer_host=%
suid=2
with_check_option=0
timestamp=2015-01-23 08:57:53
create-version=1
source=SELECT  musicvideo.*,  files.strFileName as strFileName,  path.strPath as strPath,  files.playCount as playCount,  files.lastPlayed as lastPlayed,  files.dateAdded as dateAdded,   bookmark.timeInSeconds AS resumeTimeInSeconds,   bookmark.totalTimeInSeconds AS totalTimeInSeconds FROM musicvideo  JOIN files ON    files.idFile=musicvideo.idFile  JOIN path ON    path.idPath=files.idPath  LEFT JOIN bookmark ON    bookmark.idFile=musicvideo.idFile AND bookmark.type=1
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `video90`.`musicvideo`.`idMVideo` AS `idMVideo`,`video90`.`musicvideo`.`idFile` AS `idFile`,`video90`.`musicvideo`.`c00` AS `c00`,`video90`.`musicvideo`.`c01` AS `c01`,`video90`.`musicvideo`.`c02` AS `c02`,`video90`.`musicvideo`.`c03` AS `c03`,`video90`.`musicvideo`.`c04` AS `c04`,`video90`.`musicvideo`.`c05` AS `c05`,`video90`.`musicvideo`.`c06` AS `c06`,`video90`.`musicvideo`.`c07` AS `c07`,`video90`.`musicvideo`.`c08` AS `c08`,`video90`.`musicvideo`.`c09` AS `c09`,`video90`.`musicvideo`.`c10` AS `c10`,`video90`.`musicvideo`.`c11` AS `c11`,`video90`.`musicvideo`.`c12` AS `c12`,`video90`.`musicvideo`.`c13` AS `c13`,`video90`.`musicvideo`.`c14` AS `c14`,`video90`.`musicvideo`.`c15` AS `c15`,`video90`.`musicvideo`.`c16` AS `c16`,`video90`.`musicvideo`.`c17` AS `c17`,`video90`.`musicvideo`.`c18` AS `c18`,`video90`.`musicvideo`.`c19` AS `c19`,`video90`.`musicvideo`.`c20` AS `c20`,`video90`.`musicvideo`.`c21` AS `c21`,`video90`.`musicvideo`.`c22` AS `c22`,`video90`.`musicvideo`.`c23` AS `c23`,`video90`.`files`.`strFilename` AS `strFileName`,`video90`.`path`.`strPath` AS `strPath`,`video90`.`files`.`playCount` AS `playCount`,`video90`.`files`.`lastPlayed` AS `lastPlayed`,`video90`.`files`.`dateAdded` AS `dateAdded`,`video90`.`bookmark`.`timeInSeconds` AS `resumeTimeInSeconds`,`video90`.`bookmark`.`totalTimeInSeconds` AS `totalTimeInSeconds` from (((`video90`.`musicvideo` join `video90`.`files` on((`video90`.`files`.`idFile` = `video90`.`musicvideo`.`idFile`))) join `video90`.`path` on((`video90`.`path`.`idPath` = `video90`.`files`.`idPath`))) left join `video90`.`bookmark` on(((`video90`.`bookmark`.`idFile` = `video90`.`musicvideo`.`idFile`) and (`video90`.`bookmark`.`type` = 1))))
