#!/bin/bash

WORKDIR=$(pwd)
export WORKDIR
PATH=${WORKDIR}/armv7-marvell-linux-gnueabi-softfp_i686/bin:$PATH
export PATH
CC=arm-marvell-linux-gnueabi-gcc
export CC
export CROSS_COMPILE=arm-marvell-linux-gnueabi-
CXX=${CROSS_COMPILE}g++
export CXX
RANLIB=${CROSS_COMPILE}ranlib
export RANLIB
LD=${CROSS_COMPILE}ld
export LD
STRIP=${CROSS_COMPILE}strip
export STRIP

cd linux-3.2.34/
  make clean
  make ARCH=arm menuconfig
  make ARCH=arm modules -j4

