TYPE=VIEW
query=select `music48`.`song`.`idSong` AS `idSong`,`music48`.`song`.`strArtists` AS `strArtists`,`music48`.`song`.`strGenres` AS `strGenres`,`music48`.`song`.`strTitle` AS `strTitle`,`music48`.`song`.`iTrack` AS `iTrack`,`music48`.`song`.`iDuration` AS `iDuration`,`music48`.`song`.`iYear` AS `iYear`,`music48`.`song`.`strFileName` AS `strFileName`,`music48`.`song`.`strMusicBrainzTrackID` AS `strMusicBrainzTrackID`,`music48`.`song`.`iTimesPlayed` AS `iTimesPlayed`,`music48`.`song`.`iStartOffset` AS `iStartOffset`,`music48`.`song`.`iEndOffset` AS `iEndOffset`,`music48`.`song`.`lastplayed` AS `lastplayed`,`music48`.`song`.`rating` AS `rating`,`music48`.`song`.`comment` AS `comment`,`music48`.`song`.`idAlbum` AS `idAlbum`,`music48`.`album`.`strAlbum` AS `strAlbum`,`music48`.`path`.`strPath` AS `strPath`,`music48`.`karaokedata`.`iKaraNumber` AS `iKaraNumber`,`music48`.`karaokedata`.`iKaraDelay` AS `iKaraDelay`,`music48`.`karaokedata`.`strKaraEncoding` AS `strKaraEncoding`,`music48`.`album`.`bCompilation` AS `bCompilation`,`music48`.`album`.`strArtists` AS `strAlbumArtists` from (((`music48`.`song` join `music48`.`album` on((`music48`.`song`.`idAlbum` = `music48`.`album`.`idAlbum`))) join `music48`.`path` on((`music48`.`song`.`idPath` = `music48`.`path`.`idPath`))) left join `music48`.`karaokedata` on((`music48`.`song`.`idSong` = `music48`.`karaokedata`.`idSong`)))
md5=740b697fa4c0f108b26a242c8e68e9c7
updatable=0
algorithm=0
definer_user=kodi
definer_host=%
suid=2
with_check_option=0
timestamp=2015-01-23 08:57:39
create-version=1
source=SELECT         song.idSong AS idSong,         song.strArtists AS strArtists,        song.strGenres AS strGenres,        strTitle,         iTrack, iDuration,         song.iYear AS iYear,         strFileName,         strMusicBrainzTrackID,         iTimesPlayed, iStartOffset, iEndOffset,         lastplayed, rating, comment,         song.idAlbum AS idAlbum,         strAlbum,         strPath,         iKaraNumber, iKaraDelay, strKaraEncoding,        album.bCompilation AS bCompilation,        album.strArtists AS strAlbumArtists FROM song  JOIN album ON    song.idAlbum=album.idAlbum  JOIN path ON    song.idPath=path.idPath  LEFT OUTER JOIN karaokedata ON    song.idSong=karaokedata.idSong
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `music48`.`song`.`idSong` AS `idSong`,`music48`.`song`.`strArtists` AS `strArtists`,`music48`.`song`.`strGenres` AS `strGenres`,`music48`.`song`.`strTitle` AS `strTitle`,`music48`.`song`.`iTrack` AS `iTrack`,`music48`.`song`.`iDuration` AS `iDuration`,`music48`.`song`.`iYear` AS `iYear`,`music48`.`song`.`strFileName` AS `strFileName`,`music48`.`song`.`strMusicBrainzTrackID` AS `strMusicBrainzTrackID`,`music48`.`song`.`iTimesPlayed` AS `iTimesPlayed`,`music48`.`song`.`iStartOffset` AS `iStartOffset`,`music48`.`song`.`iEndOffset` AS `iEndOffset`,`music48`.`song`.`lastplayed` AS `lastplayed`,`music48`.`song`.`rating` AS `rating`,`music48`.`song`.`comment` AS `comment`,`music48`.`song`.`idAlbum` AS `idAlbum`,`music48`.`album`.`strAlbum` AS `strAlbum`,`music48`.`path`.`strPath` AS `strPath`,`music48`.`karaokedata`.`iKaraNumber` AS `iKaraNumber`,`music48`.`karaokedata`.`iKaraDelay` AS `iKaraDelay`,`music48`.`karaokedata`.`strKaraEncoding` AS `strKaraEncoding`,`music48`.`album`.`bCompilation` AS `bCompilation`,`music48`.`album`.`strArtists` AS `strAlbumArtists` from (((`music48`.`song` join `music48`.`album` on((`music48`.`song`.`idAlbum` = `music48`.`album`.`idAlbum`))) join `music48`.`path` on((`music48`.`song`.`idPath` = `music48`.`path`.`idPath`))) left join `music48`.`karaokedata` on((`music48`.`song`.`idSong` = `music48`.`karaokedata`.`idSong`)))
